### ISSUE TITLE
Create project error

### ISSUE THREAD

**Issue by errnull** [XTStudio/XTStudio#1]
## Steps to Reproduce
> $ npm i xt-studio --save
> $ ./node_modules/.bin/xt init
> $ npm run debug

#### Version
![2018-11-15 11 09 39](https://user-images.githubusercontent.com/28481578/48527694-008a4e00-e8c7-11e8-8884-c1e2b47862da.png)

#### Port
<img width="652" alt="2018-11-15 11 13 20" src="https://user-images.githubusercontent.com/28481578/48527845-7b536900-e8c7-11e8-9440-dd9ad2a899a7.png">

#### Logs

\>xt_code@1.0.0 debug /Users/errnull/Desktop/Code_errnull/XT_Code
\>xt debug

/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/tsify/lib/Tsifier.js:80
                                config = tsconfig.readFileSync(configFile);
                                                  ^

TypeError: tsconfig.readFileSync is not a function
    at parseOptions (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/tsify/lib/Tsifier.js:80:23)
    at new Tsifier (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/tsify/lib/Tsifier.js:148:23)
    at tsify (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/tsify/index.js:19:16)
    at Browserify.plugin (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/browserify/index.js:385:9)
    at SrcBundler.createBrowserify (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/xt-studio/index.js:230:14)
    at SrcBundler.watch (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/xt-studio/index.js:247:24)
    at SrcBundler.debug (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/xt-studio/index.js:304:14)
    at Object.<anonymous> (/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/xt-studio/index.js:373:16)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xt_code@1.0.0 debug: `xt debug`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xt_code@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/errnull/.npm/_logs/2018-11-15T03_12_53_021Z-debug.log

>  /Users/errnull/.npm/_logs/2018-11-15T03_12_53_021Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/11.0.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'debug' ]
2 info using npm@6.4.1
3 info using node@v11.0.0
4 verbose run-script [ 'predebug', 'debug', 'postdebug' ]
5 info lifecycle xt_code@1.0.0~predebug: xt_code@1.0.0
6 info lifecycle xt_code@1.0.0~debug: xt_code@1.0.0
7 verbose lifecycle xt_code@1.0.0~debug: unsafe-perm in lifecycle true
8 verbose lifecycle xt_code@1.0.0~debug: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/errnull/Desktop/Code_errnull/XT_Code/node_modules/.bin:/Users/errnull/flutter/bin:/Users/errnull/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/errnull/flutter/bin:/Users/errnull/bin
9 verbose lifecycle xt_code@1.0.0~debug: CWD: /Users/errnull/Desktop/Code_errnull/XT_Code
10 silly lifecycle xt_code@1.0.0~debug: Args: [ '-c', 'xt debug' ]
11 silly lifecycle xt_code@1.0.0~debug: Returned: code: 1  signal: null
12 info lifecycle xt_code@1.0.0~debug: Failed to exec debug script
13 verbose stack Error: xt_code@1.0.0 debug: `xt debug`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid xt_code@1.0.0
15 verbose cwd /Users/errnull/Desktop/Code_errnull/XT_Code
16 verbose Darwin 18.0.0
17 verbose argv "/usr/local/Cellar/node/11.0.0/bin/node" "/usr/local/bin/npm" "run" "debug"
18 verbose node v11.0.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error xt_code@1.0.0 debug: `xt debug`
22 error Exit status 1
23 error Failed at the xt_code@1.0.0 debug script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by PonyCui** [comment]
You forgot run `npm init` first.

**Comment by errnull** [comment]
when I run ```npm i xt-studio --save```
It logs：
\> fsevents@1.2.4 install /Users/errnull/Desktop/Code_errnull/XT_Code/HelloXT/node_modules/fsevents
\> node install
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v67-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@11.0.0 (node-v67 ABI, unknown) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/errnull/.node-gyp/11.0.0/include/node/v8.h:2537:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/errnull/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
2 warnings generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/errnull/Desktop/Code_errnull/XT_Code/HelloXT/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN helloxt@1.0.0 No description
npm WARN helloxt@1.0.0 No repository field.

+ xt-studio@0.6.0
added 488 packages from 315 contributors and audited 3610 packages in 29.593s
found 0 vulnerabilities

It seems that  something wrong

**Comment by errnull** [comment]
And when I run ```npm run web```
It logs:
\> helloxt@1.0.0 web /Users/errnull/Desktop/Code_errnull/XT_Code/HelloXT
\> cd platform/web && http-server -c-1 -s -o
sh: http-server: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! helloxt@1.0.0 web: `cd platform/web && http-server -c-1 -s -o`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the helloxt@1.0.0 web script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/errnull/.npm/_logs/2018-11-15T12_34_27_669Z-debug.log

✅It seems I should run ```npm install -g http-server``` first

**Comment by errnull** [comment]
When I run ```pod install```
It logs:
fatal: repository 'https://github.com/XTStudio/UULog-iOS.git/' not found

**Comment by PonyCui** [comment]
It will fix on next release.

**Comment by PonyCui** [comment]
Bug-fixed, use 0.7.0 release.
